version: '{build}'
configuration: Debug
cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- inspectcode -> appveyor.yml
- packages -> **\packages.config
install:
- cmd: >-
    git submodule update --init --recursive

    choco install resharper-clt -y

    choco install nvika -y

    appveyor DownloadFile https://github.com/peppy/CodeFileSanity/releases/download/v0.1/CodeFileSanity.exe
before_build:
- cmd: >-
    CodeFileSanity.exe

    nuget restore
build:
  project: osu-framework.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    inspectcode /o="inspectcodereport.xml" /caches-home="inspectcode" osu-framework.sln

    NVika parsereport "inspectcodereport.xml"
artifacts:
- path: inspectcodereport.xml